import type { ProductionLineTemplate } from "@/types/editor";

export const LINE_TEMPLATES: ProductionLineTemplate[] = [
  {
    id: "classic_cup",
    name: "Klassik muzqaymoq (stakan)",
    description: "Sut → Smes → Pasterizatsiya → Yetilish → Muzlatish → To'ldirish → Qotirish → Qadoqlash",
    stages: [
      { subtype: "raw_warehouse", label: "Xom ashyo" },
      { subtype: "reception_tank", label: "Sut qabuli" },
      { subtype: "mixing_tank_heated", label: "Aralashtirish (70°C)" },
      { subtype: "pasteurizer_plate", label: "Pasterizatsiya" },
      { subtype: "homogenizer", label: "Gomogenizatsiya" },
      { subtype: "plate_cooler", label: "Sovutish (4°C)" },
      { subtype: "aging_tank", label: "Yetilish (4-8 soat)" },
      { subtype: "continuous_freezer", label: "Muzlatish (-6°C)" },
      { subtype: "fruit_feeder", label: "Qo'shimchalar" },
      { subtype: "filling_machine", label: "Stakanga to'ldirish" },
      { subtype: "hardening_tunnel", label: "Qotirish (-40°C)" },
      { subtype: "metal_detector", label: "Metall detektor" },
      { subtype: "check_weigher", label: "Tortish nazorati" },
      { subtype: "packaging_machine", label: "Qadoqlash" },
      { subtype: "box_packer", label: "Kartonga joylashtirish" },
      { subtype: "cold_warehouse", label: "Sovuq sklad (-25°C)" },
    ],
  },
  {
    id: "cone",
    name: "Kulokli muzqaymoq",
    description: "Klassik + kulok tayyorlash + shokolad qoplash",
    stages: [
      { subtype: "raw_warehouse", label: "Xom ashyo" },
      { subtype: "mixing_tank_heated", label: "Aralashtirish" },
      { subtype: "pasteurizer_plate", label: "Pasterizatsiya" },
      { subtype: "homogenizer", label: "Gomogenizatsiya" },
      { subtype: "plate_cooler", label: "Sovutish" },
      { subtype: "aging_tank", label: "Yetilish" },
      { subtype: "continuous_freezer", label: "Muzlatish" },
      { subtype: "cone_line", label: "Kulokga to'ldirish" },
      { subtype: "hardening_tunnel", label: "Qotirish" },
      { subtype: "packaging_machine", label: "Qadoqlash" },
      { subtype: "cold_warehouse", label: "Sovuq sklad" },
    ],
  },
  {
    id: "stick_bar",
    name: "Stikli muzqaymoq (eskimo)",
    description: "Klassik + ekstruziya + shokolad qoplash + stik kiritish",
    stages: [
      { subtype: "raw_warehouse", label: "Xom ashyo" },
      { subtype: "mixing_tank_heated", label: "Aralashtirish" },
      { subtype: "pasteurizer_plate", label: "Pasterizatsiya" },
      { subtype: "homogenizer", label: "Gomogenizatsiya" },
      { subtype: "plate_cooler", label: "Sovutish" },
      { subtype: "aging_tank", label: "Yetilish" },
      { subtype: "continuous_freezer", label: "Muzlatish" },
      { subtype: "stick_bar_line", label: "Stikli shakllantirish" },
      { subtype: "hardening_tunnel", label: "Qotirish" },
      { subtype: "packaging_machine", label: "Qadoqlash" },
      { subtype: "cold_warehouse", label: "Sovuq sklad" },
    ],
  },
  {
    id: "sandwich",
    name: "Sendvich / briket",
    description: "Klassik + pechenye + pressovka",
    stages: [
      { subtype: "raw_warehouse", label: "Xom ashyo" },
      { subtype: "mixing_tank_heated", label: "Aralashtirish" },
      { subtype: "pasteurizer_plate", label: "Pasterizatsiya" },
      { subtype: "homogenizer", label: "Gomogenizatsiya" },
      { subtype: "plate_cooler", label: "Sovutish" },
      { subtype: "aging_tank", label: "Yetilish" },
      { subtype: "continuous_freezer", label: "Muzlatish" },
      { subtype: "sandwich_line", label: "Sendvich shakllantirish" },
      { subtype: "hardening_tunnel", label: "Qotirish" },
      { subtype: "packaging_machine", label: "Qadoqlash" },
      { subtype: "cold_warehouse", label: "Sovuq sklad" },
    ],
  },
  {
    id: "bulk",
    name: "Bulk (oilaviy qadoq)",
    description: "Katta idishlarga to'ldirish (1-5 litr)",
    stages: [
      { subtype: "raw_warehouse", label: "Xom ashyo" },
      { subtype: "mixing_tank_heated", label: "Aralashtirish" },
      { subtype: "pasteurizer_plate", label: "Pasterizatsiya" },
      { subtype: "homogenizer", label: "Gomogenizatsiya" },
      { subtype: "plate_cooler", label: "Sovutish" },
      { subtype: "aging_tank", label: "Yetilish" },
      { subtype: "continuous_freezer", label: "Muzlatish" },
      { subtype: "filling_machine", label: "Katta idishga to'ldirish" },
      { subtype: "hardening_tunnel", label: "Qotirish" },
      { subtype: "cold_warehouse", label: "Sovuq sklad" },
    ],
  },
];
